<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CDC2-L-138LY8D" failures="1" tests="6" name="Test Cases" time="0.072" errors="0" timestamp="2022-08-08T11:07:19 IST">
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase1" time="0.015">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase2" time="0.014"/>
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase1" time="0.001">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase1" time="0.001">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase1" time="0.001">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRunFailedTestCases.SimpleTestCase" name="testCase1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at ReRunFailedTestCases.SimpleTestCase.testCase1(SimpleTestCase.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- Test Cases -->
